# Generated by Django 5.0.7 on 2024-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.IntegerField(),
        ),
    ]
