# Generated by Django 5.0.7 on 2024-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_room_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_number",
        ),
        migrations.AddField(
            model_name="room",
            name="room",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
