# Generated by Django 5.0.7 on 2024-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_room_number_room_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
